# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9747fc361959b5ffaae2fda5f77af0b5f8bcb0924a8410b949479142125f9d63850e0b553bda164e79ae51c8d05db233d713f83ad054df2664b46b56265fefe

test:
  secret_key_base: 4c09c318d51d4da9346f4e84b75bb8b95fe75aa0f95d2b564ec2957f6e1abbe0a235545a61b2a17527762d8feac10fe20d2bd590b22c6403d54a84192041731d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
